apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: novamarket-scale-hpa-rps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: novamarket-scale
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_rps
        target:
          type: AverageValue
          averageValue: 10