@startuml

title Оформление заказа
actor Пользователь
participant API_шлюз
participant Сервис_заказов
participant Сервис_товаров
participant Сервис_оплаты
participant Сервис_доставки
participant Сервис_нотификаций
participant Внешняя_платежная_система

Пользователь -> API_шлюз : Запрос: Создание заказа
API_шлюз -> Сервис_заказов : Запрос: Создание заказа
group Отправляет одно событие, но читает его 2 сервиса
    Сервис_заказов ->> Сервис_товаров: Событие: 'OrderCreated'
    Сервис_заказов ->> Сервис_нотификаций: Событие: 'OrderCreated'
end

alt Товар забронирован

    Сервис_товаров ->> Сервис_заказов: Событие: 'StockReservationSucceeded'
    group Отправляет одно событие, но читает его 2 сервиса
        Сервис_заказов ->> Сервис_оплаты: Событие: 'OrderConfirmed'
        Сервис_заказов ->> Сервис_нотификаций: Событие: 'OrderConfirmed'
    end
    Сервис_заказов -> API_шлюз: Ответ: Заказ создан
    API_шлюз -> Пользователь: Ответ: Заказ создан

    Пользователь -> API_шлюз : Запрос: Оплата
    API_шлюз -> Сервис_оплаты : Запрос: Оплата
    Сервис_оплаты -> Внешняя_платежная_система: Запрос: Оплата

    alt Оплата успешна

        Внешняя_платежная_система -> Сервис_оплаты: Ответ: Оплата успешна
        group Отправляет одно событие, но читает его 2 сервиса
            Сервис_оплаты ->> Сервис_заказов: Событие: 'PaymentSucceeded'
            Сервис_оплаты ->> Сервис_нотификаций: Событие: 'PaymentSucceeded'
        end
        Сервис_оплаты -> API_шлюз : Ответ: Оплата успешна
        API_шлюз -> Пользователь : Ответ: Оплата успешна

        Сервис_заказов ->> Сервис_доставки: Событие: 'OrderPaid'
        Сервис_доставки ->> Сервис_доставки: Создание доставки
        group Отправляет одно событие, но читает его 2 сервиса
            Сервис_доставки ->> Сервис_заказов: Событие: 'DeliveryCreated'
            Сервис_доставки ->> Сервис_нотификаций: Событие: 'DeliveryCreated'
        end

    else Ошибка при оплате

        Внешняя_платежная_система -> Сервис_оплаты: Ответ: Ошибка при оплате
        group Отправляет одно событие, но читает его 2 сервиса
            Сервис_оплаты ->> Сервис_заказов: Событие: 'PaymentFailed'
            Сервис_оплаты ->> Сервис_нотификаций: Событие: 'PaymentFailed'
        end
        Сервис_оплаты -> API_шлюз : Ответ: Ошибка при оплате
        API_шлюз -> Пользователь : Ответ: Ошибка при оплате

        Сервис_заказов ->> Сервис_товаров: Событие: 'OrderCancelled'
        Сервис_товаров ->> Сервис_каталога: Событие: 'StockReleased'

    end

else Ошибка при бронировании

    Сервис_товаров ->> Сервис_заказов: Событие: 'StockReservationFailed'
    Сервис_заказов -> Сервис_заказов: Отмена заказа

end

@enduml