@startuml

title Выбор товара
actor Пользователь
participant API_шлюз
participant Сервис_каталога
participant Сервис_товаров
participant Сервис_корзины

Сервис_товаров -> Сервис_каталога: Событие: Товар обновлен(продавцом за пределами данного сценария)

Пользователь -> API_шлюз : Запрос: Выбор товара
API_шлюз -> Сервис_каталога : Запрос: Выбор товара
Сервис_каталога -> API_шлюз: Ответ: Карточка товара
API_шлюз -> Пользователь: Ответ: Карточка товара

Пользователь -> API_шлюз : Запрос: Добавление товара в корзину
API_шлюз -> Сервис_корзины : Запрос: Добавление товара в корзину
Сервис_корзины -> API_шлюз : Ответ: Товар добавлен в корзину
API_шлюз -> Пользователь : Ответ: Товар добавлен в корзину
@enduml