apiVersion: apps/v1
kind: Deployment
metadata:
  name: novamarket-scale
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  novamarket-scale
  template:
    metadata:
      labels:
        app:  novamarket-scale
    spec:
      containers:
        - name:  novamarket-scale
          image: ghcr.io/yandex-practicum/scaletestapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "20Mi"
            limits:
              memory: "30Mi"